### ISSUE TITLE
how to change the color of the button during activation

### ISSUE THREAD

**Issue by troywweber7** [maxisam/ngx-clipboard#172]
How can I change the color of the button when it is clicked/working? By default it is green, it seems.

**Comment by troywweber7** [comment]
NVM. I figured it out. I added the following scss:
```scss
@import '../../sass/variables';

.btn-success {
	color: #fff;
	background-color: $secondaryColor;
	border-color: $secondaryColor;
}
```
